//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEğitimAkademi_Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickContact
    {
        public int QuickContactID { get; set; }
        public string NameSurname { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Intagram { get; set; }
        public string Facebook { get; set; }
        public string Lınkedın { get; set; }
        public string Twitter { get; set; }
        public string Description { get; set; }
    }
}
